/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#00478d',
        'primary-container': '#005eb8',
        'on-primary': '#ffffff',
        'on-primary-container': '#c8daff',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468c',
        'secondary': '#5d5e62',
        'secondary-container': '#e2e2e6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#636468',
        'secondary-fixed': '#e2e2e6',
        'secondary-fixed-dim': '#c5c6ca',
        'on-secondary-fixed': '#191c1e',
        'on-secondary-fixed-variant': '#45474a',
        'tertiary': '#793100',
        'tertiary-container': '#9f4300',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffcfb9',
        'tertiary-fixed': '#ffdbcb',
        'tertiary-fixed-dim': '#ffb691',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#793100',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'outline': '#727783',
        'outline-variant': '#c2c6d4',
        'background': '#f9f9fc',
        'on-background': '#1a1c1e',
        'surface': '#f9f9fc',
        'on-surface': '#1a1c1e',
        'surface-dim': '#dadadc',
        'surface-bright': '#f9f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'on-surface-variant': '#424752',
        'surface-tint': '#005db6',
        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        'inverse-primary': '#a9c7ff',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
}
